-- =====================================================
-- Create RPC function to handle profile upsert with arrays
-- =====================================================

CREATE OR REPLACE FUNCTION upsert_profile_with_arrays(
    p_id UUID,
    p_payment_model TEXT DEFAULT NULL,
    p_subscription_package TEXT DEFAULT NULL,
    p_first_name TEXT DEFAULT NULL,
    p_last_name TEXT DEFAULT NULL,
    p_phone TEXT DEFAULT NULL,
    p_city TEXT DEFAULT NULL,
    p_state TEXT DEFAULT NULL,
    p_date_of_birth TEXT DEFAULT NULL,
    p_gender TEXT DEFAULT NULL,
    p_height NUMERIC DEFAULT NULL,
    p_weight NUMERIC DEFAULT NULL,
    p_chest NUMERIC DEFAULT NULL,
    p_waist NUMERIC DEFAULT NULL,
    p_hips NUMERIC DEFAULT NULL,
    p_medical_conditions TEXT[] DEFAULT NULL,
    p_injuries TEXT DEFAULT NULL,
    p_medications TEXT DEFAULT NULL,
    p_doctor_clearance TEXT DEFAULT NULL,
    p_fitness_goals TEXT[] DEFAULT NULL,
    p_specific_goal TEXT DEFAULT NULL,
    p_target_date TEXT DEFAULT NULL,
    p_current_activity_level TEXT DEFAULT NULL,
    p_fitness_level TEXT DEFAULT NULL,
    p_emergency_contact_name TEXT DEFAULT NULL,
    p_emergency_contact_phone TEXT DEFAULT NULL,
    p_emergency_contact_relationship TEXT DEFAULT NULL,
    p_preferred_days TEXT[] DEFAULT NULL,
    p_sessions_per_week INTEGER DEFAULT NULL,
    p_preferred_workout_times TEXT[] DEFAULT NULL,
    p_liability_waiver_accepted BOOLEAN DEFAULT FALSE,
    p_terms_accepted BOOLEAN DEFAULT FALSE,
    p_photo_consent BOOLEAN DEFAULT FALSE,
    p_preferred_payment_method TEXT DEFAULT NULL,
    p_payment_setup_required BOOLEAN DEFAULT TRUE,
    p_payment_setup_status TEXT DEFAULT 'pending',
    p_referral_source TEXT DEFAULT NULL,
    p_dietary_restrictions TEXT[] DEFAULT NULL,
    p_onboarding_completed_at TEXT DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    INSERT INTO public.profiles (
        id,
        payment_model,
        subscription_package,
        first_name,
        last_name,
        phone,
        city,
        state,
        date_of_birth,
        gender,
        height,
        weight,
        chest,
        waist,
        hips,
        medical_conditions,
        injuries,
        medications,
        doctor_clearance,
        fitness_goals,
        specific_goal,
        target_date,
        current_activity_level,
        fitness_level,
        emergency_contact_name,
        emergency_contact_phone,
        emergency_contact_relationship,
        preferred_days,
        sessions_per_week,
        preferred_workout_times,
        liability_waiver_accepted,
        terms_accepted,
        photo_consent,
        preferred_payment_method,
        payment_setup_required,
        payment_setup_status,
        referral_source,
        dietary_restrictions,
        onboarding_completed_at,
        updated_at
    ) VALUES (
        p_id,
        p_payment_model,
        p_subscription_package,
        p_first_name,
        p_last_name,
        p_phone,
        p_city,
        p_state,
        p_date_of_birth::DATE,
        p_gender,
        p_height,
        p_weight,
        p_chest,
        p_waist,
        p_hips,
        p_medical_conditions,
        p_injuries,
        p_medications,
        p_doctor_clearance,
        p_fitness_goals,
        p_specific_goal,
        CASE WHEN p_target_date IS NOT NULL THEN p_target_date::DATE ELSE NULL END,
        p_current_activity_level,
        p_fitness_level,
        p_emergency_contact_name,
        p_emergency_contact_phone,
        p_emergency_contact_relationship,
        p_preferred_days,
        p_sessions_per_week,
        p_preferred_workout_times,
        p_liability_waiver_accepted,
        p_terms_accepted,
        p_photo_consent,
        p_preferred_payment_method,
        p_payment_setup_required,
        p_payment_setup_status,
        p_referral_source,
        p_dietary_restrictions,
        CASE WHEN p_onboarding_completed_at IS NOT NULL THEN p_onboarding_completed_at::TIMESTAMPTZ ELSE NULL END,
        NOW()
    )
    ON CONFLICT (id) DO UPDATE SET
        payment_model = EXCLUDED.payment_model,
        subscription_package = EXCLUDED.subscription_package,
        first_name = EXCLUDED.first_name,
        last_name = EXCLUDED.last_name,
        phone = EXCLUDED.phone,
        city = EXCLUDED.city,
        state = EXCLUDED.state,
        date_of_birth = EXCLUDED.date_of_birth,
        gender = EXCLUDED.gender,
        height = EXCLUDED.height,
        weight = EXCLUDED.weight,
        chest = EXCLUDED.chest,
        waist = EXCLUDED.waist,
        hips = EXCLUDED.hips,
        medical_conditions = EXCLUDED.medical_conditions,
        injuries = EXCLUDED.injuries,
        medications = EXCLUDED.medications,
        doctor_clearance = EXCLUDED.doctor_clearance,
        fitness_goals = EXCLUDED.fitness_goals,
        specific_goal = EXCLUDED.specific_goal,
        target_date = EXCLUDED.target_date,
        current_activity_level = EXCLUDED.current_activity_level,
        fitness_level = EXCLUDED.fitness_level,
        emergency_contact_name = EXCLUDED.emergency_contact_name,
        emergency_contact_phone = EXCLUDED.emergency_contact_phone,
        emergency_contact_relationship = EXCLUDED.emergency_contact_relationship,
        preferred_days = EXCLUDED.preferred_days,
        sessions_per_week = EXCLUDED.sessions_per_week,
        preferred_workout_times = EXCLUDED.preferred_workout_times,
        liability_waiver_accepted = EXCLUDED.liability_waiver_accepted,
        terms_accepted = EXCLUDED.terms_accepted,
        photo_consent = EXCLUDED.photo_consent,
        preferred_payment_method = EXCLUDED.preferred_payment_method,
        payment_setup_required = EXCLUDED.payment_setup_required,
        payment_setup_status = EXCLUDED.payment_setup_status,
        referral_source = EXCLUDED.referral_source,
        dietary_restrictions = EXCLUDED.dietary_restrictions,
        onboarding_completed_at = EXCLUDED.onboarding_completed_at,
        updated_at = NOW();
END;
$$;

-- Grant execute permission
GRANT EXECUTE ON FUNCTION upsert_profile_with_arrays TO authenticated, anon, service_role;

